export const GET_ALL_ACCESSORIES = "GET_ALL_ACCESSORIES";
export const GET_AVAILABLE_FOR_INVOICE = "GET_AVAILABLE_FOR_INVOICE";
export const ADD_ACCESSORIES = "ADD_ACCESSORIES";
export const IMPORT_ACCESSORIES = "IMPORT_ACCESSORIES";
export const EXPORT_ACCESSORIES = "EXPORT_ACCESSORIES";
export const EDIT_ACCESSORIES = "EDIT_ACCESSORIES";
export const DELETE_ACCESSORIES = "DELETE_ACCESSORIES";
