export const GET_ALL_EQUIPMENT = "GET_ALL_EQUIPMENT";
export const ADD_EQUIPMENT = "ADD_EQUIPMENT";
export const EDIT_EQUIPMENT = "EDIT_EQUIPMENT";
export const DELETE_EQUIPMENT = "DELETE_EQUIPMENT";
