export const GET_ALL_ACCESSORIES = "GET_ALL_ACCESSORIES";
export const ADD_ACCESSORIES = "ADD_ACCESSORIES";
export const EDIT_ACCESSORIES = "EDIT_ACCESSORIES";
export const DELETE_ACCESSORIES = "DELETE_ACCESSORIES";
