export const APP_SHOW_MODAL = "APP_SHOW_MODAL";
export const APP_SET_MOVIE = "APP_SET_MOVIE";
export const APP_CLEAR_MODAL = "APP_CLEAR_MODAL";
export const APP_GET_MOVIE_DETAILS = "APP_GET_MOVIE_DETAILS";
