export const GET_ALL_CLIENTS = "GET_ALL_CLIENTS";
export const GET_CLIENT = "GET_CLIENT";
export const GET_CLIENT_REQUESTS = "GET_CLIENT_REQUESTS";
export const ADD_CLIENTS = "ADD_CLIENTS";
export const EDIT_CLIENTS = "EDIT_CLIENTS";
export const DELETE_CLIENTS = "DELETE_CLIENTS";
