export const GET_ALL_BRIGADIERS = "GET_ALL_BRIGADIERS";
export const GET_BRIGADIER = "GET_BRIGADIER";
export const GET_BRIGADIER_REQUESTS = "GET_BRIGADIER_REQUESTS";
export const ADD_BRIGADIERS = "ADD_BRIGADIERS";
export const EDIT_BRIGADIERS = "EDIT_BRIGADIERS";
export const DELETE_BRIGADIERS = "DELETE_BRIGADIERS";
