export const CLEAR_CLIENTS_STATE = "CLEAR_CLIENTS_STATE";
export const CLEAR_REQUESTS_STATE = "CLEAR_REQUESTS_STATE";
export const CLEAR_REQUEST_REPORTS_STATE = "CLEAR_REQUEST_REPORTS_STATE";
export const CLEAR_BRIGADIERS_STATE = "CLEAR_BRIGADIERS_STATE";
export const CLEAR_INVOICES_STATE = "CLEAR_INVOICES_STATE";
