export const GET_ALL_INVOICES = "GET_ALL_INVOICES";
export const GET_FOR_BRIGADIER = "GET_FOR_BRIGADIER";
export const GET_INVOICE_FILE = "GET_INVOICE_FILE";
export const GET_INVOICE_ITEMS = "GET_INVOICE_ITEMS";
export const CREATE_INVOICE = "CREATE_INVOICE";
