export const GET_ALL_REQUESTS = "GET_ALL_REQUESTS";
export const GET_REQUEST = "GET_REQUEST";
export const ADD_REQUESTS = "ADD_REQUESTS";
export const EDIT_REQUESTS_BY_ADMIN = "EDIT_REQUESTS_BY_ADMIN";
export const EDIT_REQUESTS_BY_BRIGADIER = "EDIT_REQUESTS_BY_BRIGADIER";
export const DELETE_REQUESTS = "DELETE_REQUESTS";
