export const BRIGADIERS_COUNT = "BRIGADIERS_COUNT";
export const CLIENTS_COUNT = "CLIENTS_COUNT";
export const REQUESTS_STAT = "REQUESTS_STAT";
export const INVOICES_STAT = "INVOICES_STAT";
export const BRIGADIERS_TOP = "BRIGADIERS_TOP";
export const INSTALLED_EQUIPMENT = "INSTALLED_EQUIPMENT";
export const SOLD_ACCESSORIES = "SOLD_ACCESSORIES";
